```
Today Agenda:
- Unsupervised Machine Learning
- KMeans
```

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
mall_data = pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Clustering/Mall_Customers.csv")
mall_data.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
mall_data.columns

Index(['CustomerID', 'Genre', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [5]:
mall_data_dum = mall_data.drop('CustomerID',axis=1)
mall_data_dum.head()

    Genre  Age  Annual Income (k$)  Spending Score (1-100)
0    Male   19                  15                      39
1    Male   21                  15                      81
2  Female   20                  16                       6
3  Female   23                  16                      77
4  Female   31                  17                      40

In [6]:
mall_data_dum.isna().sum()

Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [7]:
mall_data_dum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
Genre                     200 non-null object
Age                       200 non-null int64
Annual Income (k$)        200 non-null int64
Spending Score (1-100)    200 non-null int64
dtypes: int64(3), object(1)
memory usage: 6.3+ KB

In [8]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [9]:
mall_data_dum['Genre'] = lbe.fit_transform(
    mall_data_dum['Genre'])

In [11]:
mall_data_dum['Genre'].unique()

array([1, 0], dtype=int64)

In [12]:
mall_data_dum['Genre'].value_counts()

0    112
1     88
Name: Genre, dtype: int64

In [13]:
mall_data_dum

     Genre  Age  Annual Income (k$)  Spending Score (1-100)
0        1   19                  15                      39
1        1   21                  15                      81
2        0   20                  16                       6
3        0   23                  16                      77
4        0   31                  17                      40
5        0   22                  17                      76
6        0   35                  18                       6
7        0   23                  18                      94
8        1   64                  19                       3
9        0   30                  19                      72
10       1   67                  19                      14
11       0   35                  19                      99
12       0   58                  20                      15
13       0   24                  20                      77
14       1   37                  20                      13
15       1   22                  20                      79
16       0   35                  21                      35
17       1   20                  21                      66
18       1   52                  23                      29
19       0   35                  23                      98
20       1   35                  24                      35
21       1   25                  24                      73
22       0   46                  25                       5
23       1   31                  25                      73
24       0   54                  28                      14
25       1   29                  28                      82
26       0   45                  28                      32
27       1   35                  28                      61
28       0   40                  29                      31
29       0   23                  29                      87
..     ...  ...                 ...                     ...
170      1   40                  87                      13
171      1   28                  87                      75
172      1   36                  87                      10
173      1   36                  87                      92
174      0   52                  88                      13
175      0   30                  88                      86
176      1   58                  88                      15
177      1   27                  88                      69
178      1   59                  93                      14
179      1   35                  93                      90
180      0   37                  97                      32
181      0   32                  97                      86
182      1   46                  98                      15
183      0   29                  98                      88
184      0   41                  99                      39
185      1   30                  99                      97
186      0   54                 101                      24
187      1   28                 101                      68
188      0   41                 103                      17
189      0   36                 103                      85
190      0   34                 103                      23
191      0   32                 103                      69
192      1   33                 113                       8
193      0   38                 113                      91
194      0   47                 120                      16
195      0   35                 120                      79
196      0   45                 126                      28
197      1   32                 126                      74
198      1   32                 137                      18
199      1   30                 137                      83

[200 rows x 4 columns]

Check types of scallers and know about each scaller

In [14]:
from sklearn.model_selection import train_test_split
data_train,data_test = train_test_split(mall_data_dum,
                                        random_state=2,
                                        test_size=0.25)

In [15]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=4)

In [16]:
km.fit(data_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [17]:
help(km.fit(data_train))

Help on KMeans in module sklearn.cluster.k_means_ object:

class KMeans(sklearn.base.BaseEstimator, sklearn.base.ClusterMixin, sklearn.base.TransformerMixin)
 |  KMeans(n_clusters=8, init='k-means++', n_init=10, max_iter=300, tol=0.0001, precompute_distances='auto', verbose=0, random_state=None, copy_x=True, n_jobs=None, algorithm='auto')
 |
 |  K-Means clustering
 |
 |  Read more in the :ref:`User Guide <k_means>`.
 |
 |  Parameters
 |  ----------
 |
 |  n_clusters : int, optional, default: 8
 |      The number of clusters to form as well as the number of
 |      centroids to generate.
 |
 |  init : {'k-means++', 'random' or an ndarray}
 |      Method for initialization, defaults to 'k-means++':
 |
 |      'k-means++' : selects initial cluster centers for k-mean
 |      clustering in a smart way to speed up convergence. See section
 |      Notes in k_init for more details.
 |
 |      'random': choose k observations (rows) at random from data for
 |      the initial centroids.
 |
 |      If an ndarray is passed, it should be of shape (n_clusters, n_features)
 |      and gives the initial centers.
 |
 |  n_init : int, default: 10
 |      Number of time the k-means algorithm will be run with different
 |      centroid seeds. The final results will be the best output of
 |      n_init consecutive runs in terms of inertia.
 |
 |  max_iter : int, default: 300
 |      Maximum number of iterations of the k-means algorithm for a
 |      single run.
 |
 |  tol : float, default: 1e-4
 |      Relative tolerance with regards to inertia to declare convergence
 |
 |  precompute_distances : {'auto', True, False}
 |      Precompute distances (faster but takes more memory).
 |
 |      'auto' : do not precompute distances if n_samples * n_clusters > 12
 |      million. This corresponds to about 100MB overhead per job using
 |      double precision.
 |
 |      True : always precompute distances
 |
 |      False : never precompute distances
 |
 |  verbose : int, default 0
 |      Verbosity mode.
 |
 |  random_state : int, RandomState instance or None (default)
 |      Determines random number generation for centroid initialization. Use
 |      an int to make the randomness deterministic.
 |      See :term:`Glossary <random_state>`.
 |
 |  copy_x : boolean, optional
 |      When pre-computing distances it is more numerically accurate to center
 |      the data first.  If copy_x is True (default), then the original data is
 |      not modified, ensuring X is C-contiguous.  If False, the original data
 |      is modified, and put back before the function returns, but small
 |      numerical differences may be introduced by subtracting and then adding
 |      the data mean, in this case it will also not ensure that data is
 |      C-contiguous which may cause a significant slowdown.
 |
 |  n_jobs : int or None, optional (default=None)
 |      The number of jobs to use for the computation. This works by computing
 |      each of the n_init runs in parallel.
 |
 |      ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
 |      ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
 |      for more details.
 |
 |  algorithm : "auto", "full" or "elkan", default="auto"
 |      K-means algorithm to use. The classical EM-style algorithm is "full".
 |      The "elkan" variation is more efficient by using the triangle
 |      inequality, but currently doesn't support sparse data. "auto" chooses
 |      "elkan" for dense data and "full" for sparse data.
 |
 |  Attributes
 |  ----------
 |  cluster_centers_ : array, [n_clusters, n_features]
 |      Coordinates of cluster centers. If the algorithm stops before fully
 |      converging (see ``tol`` and ``max_iter``), these will not be
 |      consistent with ``labels_``.
 |
 |  labels_ :
 |      Labels of each point
 |
 |  inertia_ : float
 |      Sum of squared distances of samples to their closest cluster center.
 |
 |  n_iter_ : int
 |      Number of iterations run.
 |
 |  Examples
 |  --------
 |
 |  >>> from sklearn.cluster import KMeans
 |  >>> import numpy as np
 |  >>> X = np.array([[1, 2], [1, 4], [1, 0],
 |  ...               [10, 2], [10, 4], [10, 0]])
 |  >>> kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
 |  >>> kmeans.labels_
 |  array([1, 1, 1, 0, 0, 0], dtype=int32)
 |  >>> kmeans.predict([[0, 0], [12, 3]])
 |  array([1, 0], dtype=int32)
 |  >>> kmeans.cluster_centers_
 |  array([[10.,  2.],
 |         [ 1.,  2.]])
 |
 |  See also
 |  --------
 |
 |  MiniBatchKMeans
 |      Alternative online implementation that does incremental updates
 |      of the centers positions using mini-batches.
 |      For large scale learning (say n_samples > 10k) MiniBatchKMeans is
 |      probably much faster than the default batch implementation.
 |
 |  Notes
 |  ------
 |  The k-means problem is solved using either Lloyd's or Elkan's algorithm.
 |
 |  The average complexity is given by O(k n T), were n is the number of
 |  samples and T is the number of iteration.
 |
 |  The worst case complexity is given by O(n^(k+2/p)) with
 |  n = n_samples, p = n_features. (D. Arthur and S. Vassilvitskii,
 |  'How slow is the k-means method?' SoCG2006)
 |
 |  In practice, the k-means algorithm is very fast (one of the fastest
 |  clustering algorithms available), but it falls in local minima. That's why
 |  it can be useful to restart it several times.
 |
 |  If the algorithm stops before fully converging (because of ``tol`` or
 |  ``max_iter``), ``labels_`` and ``cluster_centers_`` will not be consistent,
 |  i.e. the ``cluster_centers_`` will not be the means of the points in each
 |  cluster. Also, the estimator will reassign ``labels_`` after the last
 |  iteration to make ``labels_`` consistent with ``predict`` on the training
 |  set.
 |
 |  Method resolution order:
 |      KMeans
 |      sklearn.base.BaseEstimator
 |      sklearn.base.ClusterMixin
 |      sklearn.base.TransformerMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, n_clusters=8, init='k-means++', n_init=10, max_iter=300, tol=0.0001, precompute_distances='auto', verbose=0, random_state=None, copy_x=True, n_jobs=None, algorithm='auto')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X, y=None, sample_weight=None)
 |      Compute k-means clustering.
 |
 |      Parameters
 |      ----------
 |      X : array-like or sparse matrix, shape=(n_samples, n_features)
 |          Training instances to cluster. It must be noted that the data
 |          will be converted to C ordering, which will cause a memory
 |          copy if the given data is not C-contiguous.
 |
 |      y : Ignored
 |          not used, present here for API consistency by convention.
 |
 |      sample_weight : array-like, shape (n_samples,), optional
 |          The weights for each observation in X. If None, all observations
 |          are assigned equal weight (default: None)
 |
 |  fit_predict(self, X, y=None, sample_weight=None)
 |      Compute cluster centers and predict cluster index for each sample.
 |
 |      Convenience method; equivalent to calling fit(X) followed by
 |      predict(X).
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape = [n_samples, n_features]
 |          New data to transform.
 |
 |      y : Ignored
 |          not used, present here for API consistency by convention.
 |
 |      sample_weight : array-like, shape (n_samples,), optional
 |          The weights for each observation in X. If None, all observations
 |          are assigned equal weight (default: None)
 |
 |      Returns
 |      -------
 |      labels : array, shape [n_samples,]
 |          Index of the cluster each sample belongs to.
 |
 |  fit_transform(self, X, y=None, sample_weight=None)
 |      Compute clustering and transform X to cluster-distance space.
 |
 |      Equivalent to fit(X).transform(X), but more efficiently implemented.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape = [n_samples, n_features]
 |          New data to transform.
 |
 |      y : Ignored
 |          not used, present here for API consistency by convention.
 |
 |      sample_weight : array-like, shape (n_samples,), optional
 |          The weights for each observation in X. If None, all observations
 |          are assigned equal weight (default: None)
 |
 |      Returns
 |      -------
 |      X_new : array, shape [n_samples, k]
 |          X transformed in the new space.
 |
 |  predict(self, X, sample_weight=None)
 |      Predict the closest cluster each sample in X belongs to.
 |
 |      In the vector quantization literature, `cluster_centers_` is called
 |      the code book and each value returned by `predict` is the index of
 |      the closest code in the code book.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape = [n_samples, n_features]
 |          New data to predict.
 |
 |      sample_weight : array-like, shape (n_samples,), optional
 |          The weights for each observation in X. If None, all observations
 |          are assigned equal weight (default: None)
 |
 |      Returns
 |      -------
 |      labels : array, shape [n_samples,]
 |          Index of the cluster each sample belongs to.
 |
 |  score(self, X, y=None, sample_weight=None)
 |      Opposite of the value of X on the K-means objective.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape = [n_samples, n_features]
 |          New data.
 |
 |      y : Ignored
 |          not used, present here for API consistency by convention.
 |
 |      sample_weight : array-like, shape (n_samples,), optional
 |          The weights for each observation in X. If None, all observations
 |          are assigned equal weight (default: None)
 |
 |      Returns
 |      -------
 |      score : float
 |          Opposite of the value of X on the K-means objective.
 |
 |  transform(self, X)
 |      Transform X to a cluster-distance space.
 |
 |      In the new space, each dimension is the distance to the cluster
 |      centers.  Note that even if X is sparse, the array returned by
 |      `transform` will typically be dense.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix}, shape = [n_samples, n_features]
 |          New data to transform.
 |
 |      Returns
 |      -------
 |      X_new : array, shape [n_samples, k]
 |          X transformed in the new space.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : boolean, optional
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : mapping of string to any
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as pipelines). The latter have parameters of the form
 |      ``<component>__<parameter>`` so that it's possible to update each
 |      component of a nested object.
 |
 |      Returns
 |      -------
 |      self
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.BaseEstimator:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [18]:
pred = km.predict(data_train)
pred

array([0, 3, 3, 0, 1, 1, 1, 1, 2, 0, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0, 2, 2,
       2, 1, 3, 1, 2, 0, 2, 2, 0, 1, 0, 0, 1, 3, 3, 0, 1, 1, 1, 2, 2, 2,
       1, 1, 2, 3, 1, 0, 3, 0, 0, 0, 1, 0, 3, 1, 1, 2, 3, 3, 3, 0, 1, 2,
       0, 2, 2, 3, 1, 3, 1, 3, 1, 0, 2, 0, 3, 3, 3, 0, 1, 3, 1, 1, 1, 1,
       1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 3, 1, 1, 2, 0, 0, 2, 2, 3, 3, 2, 2,
       1, 3, 1, 0, 1, 0, 1, 3, 3, 1, 0, 3, 3, 1, 3, 3, 1, 2, 3, 1, 0, 3,
       1, 2, 2, 3, 1, 3, 2, 3, 0, 2, 3, 1, 3, 3, 1, 1, 3, 2])

In [19]:
pred_test = km.predict(data_test)
pred_test

array([1, 3, 2, 0, 0, 1, 1, 1, 3, 3, 1, 1, 3, 2, 2, 1, 1, 3, 3, 1, 3, 3,
       1, 2, 0, 0, 3, 3, 3, 1, 2, 1, 3, 1, 3, 1, 2, 2, 0, 1, 0, 0, 3, 0,
       1, 0, 3, 2, 2, 3])

Task:
```
- Take cust_segmentation dataset and apply kmeans algorith
- Work on different types of Scallers
```